---
- name: Renew a single self-signed certificate
  hosts: demo_host
  gather_facts: true

  tasks:
    - name: Execute self-signed cert renewal
      ansible.builtin.include_role:
        name: cert_renew_selfsigned
      vars:
        cert_path: "{{ demo_certs_dir }}/{{ service_name }}/tls.crt"
        cert_key_path: "{{ demo_certs_dir }}/{{ service_name }}/tls.key"
